spring.application.name=file-manager-server
api.client.url=http://localhost:3000

spring.security.sessionManagement.sessionCreationPolicy=STATELESS
server.servlet.session.timeout=0
server.session.persistent=false
server.session.tracking-modes=cookie

spring.datasource.url=jdbc:postgresql://filemanager-db.ctykieewsllq.eu-central-1.rds.amazonaws.com:5432/filemanager
spring.datasource.username=postgres
spring.datasource.password=parola123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.type=trace
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

aws.region=eu-central-1
aws.s3.bucketName=filemanager-uploads-valentinpopescu
aws.ses.publisher.email=valentinpopescu98@gmail.com

logging.level.root=INFO
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.web=DEBUG
logging.level.org.springframework.security.authentication=TRACE
logging.level.org.springframework.security.web.access=DEBUG
logging.level.org.springframework.security.web.authentication=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.filter=DEBUG
logging.level.org.springframework.web.servlet=DEBUG
logging.level.org.springframework.web.cors=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.apache.catalina.core=DEBUG
logging.level.org.apache.coyote.http11=DEBUG
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n
